title: Kerin Wu
logo: docs/assets/Santa_Clara_U_Seal.svg.png
description: Data Translator | Business Intelligence | Solutions Architect | Localization Expert
#show_download: true
theme: jekyll-theme-tactile
